# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  geth1:
    image: "chainsafe/chainbridge-geth:20200505131100-5586a65"
    container_name: geth1
    ports:
    - "8545:8545"

  geth2:
    image: "chainsafe/chainbridge-geth:20200505131100-5586a65"
    container_name: geth2
    ports:
    - "8546:8545"

  sub-chain:
    image: "cerebellumnetwork/pos-node:v2.29.0-rc1"
    container_name: sub-chain
    command: bash -c "/usr/local/bin/cere --dev --alice --ws-external --rpc-external"
    ports:
    - "9944:9944"
