name: Disable Relayers

on:
  workflow_dispatch:

jobs:
  kubectl-setup-and-run:
    runs-on: ["self-hosted", "cere-network-prd-deployer"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: ${{ secrets.KUBECTL_VERSION }}
      - name: Run kubectl get pods
        run: |
          # Get a list of network-relayers
          deployments=$(kubectl get deployment -n network | grep '^network-relayer' | awk '{print $1}')
          
          # Iterate over the deployments and scale each one to 0 replicas
          for deployment in $deployments; do
            echo $deployment
          done

