# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Release to prod
on:
  push:
    branches:
      - master-cere
  workflow_dispatch:

jobs:
  build:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-push-docker.yaml@1.0.0
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      org: cerebellumnetwork
      environment: prod
      image: crb-${{ github.event.repository.name }}
      repository: crb-${{ github.event.repository.name }}
      file: ./Dockerfile
    secrets: inherit

  deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-with-helm.yaml@1.0.0
    needs: build
    with:
      runs-on: '["self-hosted", "cere-network-prd-deployer"]'
      helm-repo-path: network/network-relayer
      helm-release: network-relayer
      namespace: network
      tag: ${{ needs.build.outputs.version }}
      environment: prod
    secrets: inherit
