# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Release to stage
on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-to-ecr.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large"]'
      environment: stg
      aws_account_id: ${{ vars.DEV_NETWORK_AWS_ACCOUNT_ID }}
      repository: network-relayer
      file: ./Dockerfile
    secrets: inherit
