# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

name: Release to stage
on:
  push:
    branches:
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/build-and-push-docker.yaml@master
    with:
      runs-on: '["self-hosted", "cere-network-large-workers"]'
      org: cerebellumnetwork
      environment: stage
      image: crb-${{ github.event.repository.name }}
      repository: crb-${{ github.event.repository.name }}
      file: ./Dockerfile
    secrets: inherit

  deploy:
    uses: Cerebellum-Network/reusable-workflows/.github/workflows/deploy-with-helm.yaml@master
    needs: build
    with:
      runs-on: '["self-hosted", "cere-network-stg-deployer"]'
      helm-repo-path: network/network-relayer
      helm-release: network-relayer
      namespace: network
      tag: ${{ needs.build.outputs.version }}
      environment: stage
    secrets: inherit
